### ISSUE TITLE
Configuration for the SLURM exporter

### ISSUE THREAD

**Issue by gscuser** [vpenso/prometheus-slurm-exporter#7]
Hello, I have followed your steps to build the CentOS  executable and that went fine . As a new user to prometheus I'm unsure from your instructions what to do to have a working configuration.

I have created a file prometheus.yml in my prometheus-slurm-exporter directory. Is there anything else that needs to be in that file other than what you have in your readme?
Maybe you could post an example of a basic working config.
This server is also the slurm master node of a test cluster I run.

Mine currently looks like this:
```
#
# SLURM resource manager:
#
  - job_name: 'my_slurm_exporter'

    scrape_interval:  30s
    scrape_timeout:   30s
    static_configs:
    - targets: ['localhost:8080']

```

```
$~ promtool check config prometheus.yml
Checking prometheus.yml
  FAILED: parsing YAML file prometheus.yml: yaml: unmarshal errors:
  line 4: cannot unmarshal !!seq into config.plain
```
When I run the executable
```
$~ prometheus-slurm-exporter
INFO[0000] Starting Server: :8080                        source="main.go:42"

```

When I access http://hostname:8080/graphs in the browser I get 404 page not found 
If I access http://hostname:8080/metrics it is updating with the correct scheduler info.
Im my grafana server datasource settings, when I add new datasource I get a HTTP Error.

Many thanks,
Brendan

**Comment by mtds** [comment]
Hi.

I understand you have cut and pasted the configuration from the README but that portion
is not enough. It was meant to be added to an already configured Prometheus server but 
I guess it was not clearly explained so I will update the docs.

If you don't wish to add a 'global:' stanza to your config file (but I believe you should) you have
to modify the file in this way:

```
scrape_configs:

# SLURM resource manager:

  - job_name: 'my_slurm_exporter'

    scrape_interval:  30s
    scrape_timeout:   30s
    static_configs:
    - targets: ['localhost:8080']
```

Note the additional directive ``scrape_configs``. Without this one, the config file is not completed.
More info about the config file syntax are in the official docs, in the [configuration section](https://prometheus.io/docs/prometheus/latest/configuration/configuration/).

Regarding the graph page you are a little bit confused: this exporter (and nearly all the others) will
let you access the metrics from the ``http://hostname:8080/metrics`` link as you have already saw,
but the visualization page (called expression browser) is available only on your Prometheus server
through the link ``http://prometheus.fqdn:9090/graph`` (unless you changed the default port used
by Prometheus itself).

About Grafana: if you are getting an HTTP connection error, it means you are not using the correct
address of your Prometheus instance. By default it should be something like: ``http://prometheus.fqdn:9090``.

Regards,
Matteo
